### ISSUE TITLE
Cannot disable screenshots on iOS 17 Beta

### ISSUE THREAD

**Issue by itsChri99** [0xlethe/react-native-capture-protection#21]
Hi, I noticed that on iOS 17 beta the library is not working. It works only on iOS 16.6 or below.
Can you check it?

Thank you so much
Christian

**Comment by 0xlethe** [comment]
Thanks to report issue for iOS 17 beta, i will check this issue ASAP. Thanks

**Comment by 0xlethe** [comment]
Could you please let me know which features are not working? @itsChri99

**Comment by itsChri99** [comment]
Sure, the event listener for screenshots correctly works but the black screen for preventing screenshots does not work.
So this two methods:

```
CaptureProtection.preventScreenshot();
CaptureProtection.preventScreenRecord();
```

**Comment by 0xlethe** [comment]
thanks:) i'll check for this function ASAP

**Comment by 0xlethe** [comment]
@itsChri99  hi, i fix this issue & release version.
can you try  `npm i react-native-capture-protection@1.9.0-beta` and try again?

**Comment by itsChri99** [comment]
I confirm, now it correctly works! Thank you so much!

**Comment by itsChri99** [comment]
@0xlethe I confirm, now it correctly works! Thank you so much!
