### ISSUE TITLE
iOS - Black screen when reload bundle

### ISSUE THREAD

**Issue by HossamBahi** [0xlethe/react-native-capture-protection#23]
There is a black screen appears on top of app when i reload bundle using react-native-restart ( i use it for multi lang ) or in refresh app in debug mode.

System:
    OS: macOS 13.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
    Watchman: 2023.08.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b 
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3

**Comment by 0xlethe** [comment]
Thanks for report! in black screen is appear on iOS only? or Android both? @HossamBahi

**Comment by HossamBahi** [comment]
Thanks for your response, it's appears on iOS only @0xlethe

**Comment by 0xlethe** [comment]
@HossamBahi Thanks, i will check for this issue asap :)

**Comment by 0xlethe** [comment]
@HossamBahi  hi, fix to this issue for 1.9.1. Could you all verify?

**Comment by HossamBahi** [comment]
Many thanks @0xlethe, it's resolved
