### ISSUE TITLE
I saw you solved IOS 17 screenshot protection problem.

### ISSUE THREAD

**Issue by awnigharbia** [0xlethe/react-native-capture-protection#24]
Thanks for this awesome library I would like to appreciate all the efforts. but I have a Flutter project and I need to apply your solution for IOS screenshot protection for IOS 17.

Can you post a general Swift code solution for prevnting screenshot for IOS 17?

Thanks in advance!

**Comment by 0xlethe** [comment]
@awnigharbia of course, as you know see issue (https://github.com/0xlethe/react-native-capture-protection/issues/17), i will try to convert objective c to swift after finish urgent stuff. :)

**Comment by awnigharbia** [comment]
@0xlethe Oh big thanks❤, I will wait, since my project depends on it.

**Comment by awnigharbia** [comment]
Thank you so much @0xlethe  I managed to solve it.

**Comment by ggunia** [comment]
@awnigharbia how did you manage to solve it?
