### ISSUE TITLE
CaptureProtectionListener warning on iOS

### ISSUE THREAD

**Issue by rokkoo** [0xlethe/react-native-capture-protection#39]
Hi, I'm receiving warning every time that i open the app `Sending CaptureProtectionListener with no listeners registered`.

I think this is because the library is sending the event before the the bridge is ready.

```js
"react-native": "0.73.5"
"react-native-capture-protection": "1.9.6"
iOS 17.4
```

<img src="https://github.com/0xlethe/react-native-capture-protection/assets/25004016/52aac1bf-5920-45da-acde-39a5e45fd861" alt="Description of the image" width="600">

**Comment by 0xlethe** [comment]
@rokkoo thanks for report this. i will check it & fix asap
