### ISSUE TITLE
Detect screen recording on Android

### ISSUE THREAD

**Issue by huynextlevel** [0xlethe/react-native-capture-protection#5]
Hi @0xlethe ,

Do we have any way to detect screen recording on Android?

**Comment by 0xlethe** [comment]
@huynextlevel maybe detect screen for use [accessibilityservice](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService#takeScreenshot(int,%20java.util.concurrent.Executor,%20android.accessibilityservice.AccessibilityService.TakeScreenshotCallback)), but i think didnt do it.

**Comment by huynextlevel** [comment]
Thank you so much @0xlethe !
