### ISSUE TITLE
Features Req For Android

### ISSUE THREAD

**Issue by thureintun-me** [0xlethe/react-native-capture-protection#9]
Can u add isScreenRecording features for android? We really need this features. We want to know if user start screen recording in android.

**Comment by 0xlethe** [comment]
@thureintun-me  
Hi, `isScreenRecording` is add in v1.6.0

When a virtual screen is added, it's usually for mirroring or recording.
For that reason, I decided to make sure that if a virtual screen is added, it is recording.

However, event detection when the app is launched while already recording, it must be not detected.

**Comment by thureintun-me** [comment]
Hey Thanks for you work ! but it did not quite work.It always return false  when screen recording event happen

**Comment by 0xlethe** [comment]
@thureintun-me Not good news for me. but, i try to figure out how to check record event.

Thanks for share your result.

**Comment by thureintun-me** [comment]
hope you can fix soon  ( 💯

**Comment by 0xlethe** [comment]
@thureintun-me hi, v1.9.2 support android screenshot event, but recording is not support...

**Comment by thureintun-me** [comment]
Hopefully u can support screen recording event soon

**Comment by 0xlethe** [comment]
@thureintun-me hi, can you test for v1.9.3? in Android 14, support android screenshot event, but i can't check for under version.
